### ISSUE TITLE
After installing your SPM, I can't build in my Xcode project.

### ISSUE THREAD

**Issue by Rylaa** [lukepistrol/SwiftLintPlugin#12]
<img width="308" alt="Screenshot 2023-08-07 at 17 28 48" src="https://github.com/lukepistrol/SwiftLintPlugin/assets/33103001/eb2313cc-c4aa-4e12-9ab0-655c5c48c3a7">

I've added SwiftLint to "Run Build Tool Plug-ins" in Build Phase. How can I solve this problem?

**Comment by lukepistrol** [comment]
Can you please provide more details (Xcode version, proper error message, steps taken to try resolving this issue, …)?

**Comment by Rylaa** [comment]
my xcode version is 14.3.1
i am using this package  .package(url: "https://github.com/lukepistrol/SwiftLintPlugin", from: "0.2.2")
After adding "Run Build Tool Plug-ins" to the build phase, I tried to build.

**Comment by Rylaa** [comment]
<img width="1130" alt="Screenshot 2023-08-08 at 00 02 52" src="https://github.com/lukepistrol/SwiftLintPlugin/assets/33103001/008921f9-d6b0-47c3-9465-7ffc66390f63">

**Comment by lukepistrol** [comment]
It seems that there is no `.swiftlint.yml` config file located in your projects root directory.
