### ISSUE TITLE
Enable swiftlint by default

### ISSUE THREAD

**Issue by gulivero1773** [lukepistrol/SwiftLintPlugin#14]
Need Enable swiftlint by default because I have error when I dont'n have  DISABLE_SWIFTLINT in .env file

**Comment by lukepistrol** [comment]
Could you please add more context? What error did you get? What's the general setup? A Package or an Xcode project?

**Comment by gulivero1773** [comment]
![Знімок екрана 2023-10-11 о 16 09 00](https://github.com/lukepistrol/SwiftLintPlugin/assets/61082418/e954afc3-54a1-446e-87de-69fc17056ddc)

**Comment by lukepistrol** [comment]
@gulivero1773 could you try the latest commit on the `main` branch and report back whether or not this fixes the problem?

**Comment by gulivero1773** [comment]
> @gulivero1773 could you try the latest commit on the `main` branch and report back whether or not this fixes the problem?

On main branch I don't have it problem

**Comment by lukepistrol** [comment]
Perfect. Closing this
