### ISSUE TITLE
Error when archiving in Xcode Cloud

### ISSUE THREAD

**Issue by gorka** [lukepistrol/SwiftLintPlugin#15]
Hi,

I added the TMDb package to a project in Xcode with the SPM. That package has SwiftLint and SwiftLintPlugin as dependencies.
If I archive the code locally from Xcode everything works fine, but when I try to do the same from Xcode Cloud it fails.

<img width="641" alt="Screenshot 2023-10-07 at 10 35 25 AM" src="https://github.com/lukepistrol/SwiftLintPlugin/assets/4787906/1f4ba36d-0a7d-4235-b008-47fa1c7090c6">

At first, I thought it was because I had linting issues, so I fixed them all. If I run SwiftLint locally I don't get any warning.
Checking the logs, I realized that wasn't the problem. The problem is:

`Error: You don’t have permission to save the file “f5a82a99c7fcf819a5868248f7fe3ad5ac901d06aa1bfa62415f26aba3e78b03.plist” in the folder “A4FD347F-F59D-3FB2-835A-CAC16AC563DB”.`

Then I thought, well, maybe I don't need to run the linter when archiving, and found that setting this env var (`DISABLE_SWIFTLINT`) should disable the linter. I added it to the workflow but the error is still there.

I'm using Xcode 15.0

**Comment by lukepistrol** [comment]
Could you please provide a link to the `TMDb`?

Unfortunately I haven't done anything with Xcode Cloud yet and I'm not familiar with the options one can set there when building. Maybe they don't allow build tool plugins to run on Xcode Cloud?

**Comment by gorka** [comment]
https://github.com/adamayoung/TMDb

I'm investigating and now I'm not sure that this is the plugin the package uses. It just happens to have the same name. If that's the case, please close this issue.

I also found an [open issue](https://github.com/realm/SwiftLint/issues/5205) on SwiftLint's repo.

**Comment by lukepistrol** [comment]
Can't find any reference to this package in `TMDb`'s package [manifest](https://github.com/adamayoung/TMDb/blob/main/Package.swift)

**Comment by gorka** [comment]
That's the main branch. In [version 9.0.0](https://github.com/adamayoung/TMDb/blob/9.0.0/Package.swift) (latest) you can find references:

```
plugins: [
    .plugin(name: "SwiftLintPlugin")
]
```

**Comment by lukepistrol** [comment]
Yeah that's the official plugin by [`Swiftlint`](https://github.com/realm/SwiftLint/)
