### ISSUE TITLE
SwiftLintPlugin does not support provisioning profiles

### ISSUE THREAD

**Issue by mike-code** [lukepistrol/SwiftLintPlugin#16]
I've added SwiftLintPlugin as a build phase but I have a problem building the app in the CI where I explicitly provide a provisioning profile (ie. not using automagic signing)

I have the following error
```
error: SwiftLintPlugin does not support provisioning profiles. SwiftLintPlugin does not support provisioning profiles, but provisioning profile 3cf518f8-8e85-44f7-ac02-12f1ac55de03 has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'SwiftLintPlugin' from project 'SwiftLint')
```

How can I pre-build the plugin so that xcodebuild doesn't try to sign it with that particular provisioning profile?

**Comment by lukepistrol** [comment]
What is the exact `xcodebuild` command you are using?

**Comment by mike-code** [comment]
> What is the exact `xcodebuild` command you are using?

```
xcodebuild clean build-for-testing \
	-skipPackagePluginValidation \
	-scheme "MyApp" \
	-configuration "Debug" \
	-destination platform=macOS \
	-target "MyApp" \
	CODE_SIGN_IDENTITY="my-identity" \
	PROVISIONING_PROFILE_SPECIFIER="provisioning-profile-uuid" \
	-derivedDataPath 'build/' \
	CODE_SIGN_STYLE="Manual" 
```

**Comment by lukepistrol** [comment]
It seems that the environment variables set in `xcodebuild` are passed to every target (also SPM packages). In this case you might need to find a way to only pass it to your app target somehow.

Maybe [this thread](https://forums.swift.org/t/xcode-14-beta-code-signing-issues-when-swiftpm-targets-include-resources/59685) is helpful to you (even though it's about fastlane).
