### ISSUE TITLE
Github action takes too long to fetch swiftlint plugin. 

### ISSUE THREAD

**Issue by karthikAdaptavant** [lukepistrol/SwiftLintPlugin#6]
Hi @lukepistrol, I'm using swiftlint 0.2.2. it takes too much time to fetch the artifact in github action. 
more than 30 mins and still it's not completing the fetch. i have added the screenshot. could you pls help me on fixing this issue. 

![anysnap-13-dec-2022-at-9-47-23-pm](https://user-images.githubusercontent.com/11072850/207386930-c07c2aea-b2aa-46b0-a466-a489c3b2e27b.png)

**Comment by karthikAdaptavant** [comment]
in local Xcode it's pulling without this much delay. on CI it takes too long. 
we have raised a ticked with GitHub action team as well. will update this thread if I get any insights from them.

**Comment by lukepistrol** [comment]
I just tested it on one of my projects and I cannot replicate this.

- Are you using a GitHub hosted runner?
- Which runner do you use? (e.g. macos-12)
- What does your build command look like?

**Comment by lukepistrol** [comment]
Hmm.. interesting. My configuration is pretty much the same:

```bash
set -o pipefail && xcodebuild  \
    -scheme "$SCHEME" \
    -destination "$PLATFORM" \
    -skipPackagePluginValidation \
    clean build | xcpretty
```
