### ISSUE TITLE
Unable to resolve f3586ed424d7bf5d94628332fbd0edebf1f5147f

### ISSUE THREAD

**Issue by karthikAdaptavant** [lukepistrol/SwiftLintPlugin#8]
Subject: Unable to resolve Git reference in SwiftLintPlugin

Hi Team, 

I am encountering an issue with the SwiftLintPlugin in our project. Specifically, I am seeing the following error:

fatal: reference is not a tree: f3586ed424d7bf5d94628332fbd0edebf1f5147f (on 0.2.3)

This error occurs when I try to run xcodebuild  via Fastlane and it prevents me from resolving the package dependencies.

I have tried troubleshooting this issue on my end, but I have not been able to find a solution. I suspect that this issue is related to the Git reference that SwiftLintPlugin is using, as the error message mentions a specific reference.

Could you please investigate this issue and provide a solution? Please let me know if you need any additional information or if there are any further steps I can take to troubleshoot this issue.

Thank you for your time and assistance.

![anysnap-01-apr-2023-at-5-44-16-pm](https://user-images.githubusercontent.com/11072850/229287971-d3e47463-8349-4050-8827-8cd6063a74ba.png)

Best regards,
Karthik

**Comment by lukepistrol** [comment]
Very interesting. I updated it on a couple of my projects without any problems. have you tried resetting packages caches?

**Comment by karthikAdaptavant** [comment]
Yes its still happening, i couldn't able to pull the plugin

**Comment by lukepistrol** [comment]
@karthikAdaptavant maybe it's an issue with the `swift-tools-version` then. Is Swift 5.7 available on your CI runner?
